{% set version = "0.16-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rspectra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RSpectra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RSpectra/RSpectra_{{ version }}.tar.gz
  sha256: cba5d3403d6a7d0e27abf6279fbfea6e0d0fe36b28c688bbadb8eafb3841329a

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.5
    - r-rcppeigen >=0.3.3.3.0
  run:
    - r-base
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.5
    - r-rcppeigen >=0.3.3.3.0

test:
  commands:
    - $R -e "library('RSpectra')"           # [not win]
    - "\"%R%\" -e \"library('RSpectra')\""  # [win]

about:
  home: https://github.com/yixuan/RSpectra
  license: MPL-2.0-or-later
  summary: R interface to the 'Spectra' library <https://spectralib.org/> for large-scale eigenvalue and SVD problems. It is typically used to compute a few eigenvalues/vectors of an n by n matrix, e.g., the k largest eigenvalues, which is usually more efficient than eigen() if k << n. This package provides the 'eigs()'
    function that does the similar job as in 'Matlab', 'Octave', 'Python SciPy' and 'Julia'. It also provides the 'svds()' function to calculate the largest k singular values and corresponding singular vectors of a real matrix. The matrix to be computed on can be dense, sparse, or in the form of an operator defined by the
    user.
  license_family: MPL
  license: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
